In [49]:
import math
import torch
import gpytorch
from gpytorch.utils.lanczos import lanczos_tridiag, lanczos_tridiag_to_diag
import numpy as np
from gpytorch.kernels import RBFKernel

In [51]:
nx = 100
x = torch.linspace(0,5., nx)

kern = RBFKernel()

mat = kern(x).evaluate()

In [21]:
def matmul_closure(vec):
    return mat.matmul(vec)

In [22]:
Q, T = lanczos_tridiag(matmul_closure, 10, 
                       dtype=mat.dtype, device='cpu', 
                       matrix_shape=(nx, nx))

In [17]:
T_evals, T_evecs = lanczos_tridiag_to_diag(T)

In [24]:
lan_evals = T_evals.sort()[0]
lan_evecs = Q.matmul(T_evecs)

In [54]:
e_val, e_vec = np.linalg.eig(mat.detach())
idx = np.abs(e_val).argsort()[::-1]   
e_val = torch.FloatTensor(e_val[idx].real)
e_vec = torch.FloatTensor(e_vec[:,idx].real)

In [56]:
e_val

tensor([ 3.2108e+01,  2.6123e+01,  1.8569e+01,  1.1576e+01,  6.3621e+00,
         3.1027e+00,  1.3525e+00,  5.3104e-01,  1.8918e-01,  6.1558e-02,
         1.8407e-02,  5.0844e-03,  1.3034e-03,  3.1153e-04,  6.9808e-05,
         1.4698e-05,  3.0591e-06, -1.6624e-06,  1.5788e-06, -1.4307e-06,
        -1.3236e-06,  1.2985e-06,  1.1719e-06,  1.0953e-06,  1.0040e-06,
        -9.2321e-07, -9.0039e-07, -8.7608e-07,  7.8198e-07, -7.5803e-07,
         7.5478e-07, -6.9787e-07,  6.5950e-07,  6.5950e-07, -6.0781e-07,
         5.7422e-07, -5.4638e-07,  5.0089e-07,  5.0089e-07, -4.9085e-07,
         4.7084e-07,  4.7084e-07, -4.5579e-07, -4.5579e-07, -4.2145e-07,
         4.1234e-07,  4.1234e-07,  4.0669e-07, -3.0523e-07,  3.0160e-07,
         3.0160e-07, -2.8538e-07,  2.8106e-07, -2.4779e-07,  2.3684e-07,
         2.3684e-07, -2.3178e-07, -2.0798e-07, -1.9209e-07,  1.8105e-07,
         1.8105e-07,  1.7849e-07, -1.6199e-07, -1.6199e-07,  1.5339e-07,
         1.5339e-07, -1.4113e-07, -1.4113e-07, -1.3

In [57]:
lan_evals

tensor([4.0673e-04, 7.7011e-02, 4.7000e-01, 1.3525e+00, 3.1027e+00, 6.3621e+00,
        1.1576e+01, 1.8569e+01, 2.6123e+01, 3.2108e+01],
       grad_fn=<ViewBackward>)

In [61]:
lan_evecs[:, -1]

tensor([ 0.1240,  0.1366,  0.1436,  0.1556,  0.1491,  0.1714,  0.1459,  0.1604,
         0.1715,  0.1449,  0.1491,  0.1452,  0.1494,  0.1407,  0.1486,  0.1392,
         0.1190,  0.1256,  0.1192,  0.1067,  0.0995,  0.0870,  0.0617,  0.0795,
         0.0504,  0.0428,  0.0470,  0.0289,  0.0216, -0.0005, -0.0010,  0.0023,
        -0.0062, -0.0347, -0.0311, -0.0488, -0.0295, -0.0336, -0.0548, -0.0632,
        -0.0689, -0.0714, -0.0568, -0.0682, -0.0629, -0.0685, -0.0629, -0.0408,
        -0.0839, -0.0738, -0.0877, -0.0846, -0.0675, -0.0722, -0.0584, -0.0830,
        -0.0790, -0.0781, -0.0949, -0.0928, -0.0762, -0.0982, -0.0799, -0.0977,
        -0.0982, -0.0831, -0.0970, -0.1053, -0.1101, -0.1268, -0.1182, -0.1391,
        -0.1101, -0.1189, -0.1127, -0.1196, -0.1385, -0.1266, -0.1144, -0.1208,
        -0.1384, -0.1060, -0.1143, -0.1290, -0.1214, -0.1253, -0.1052, -0.0968,
        -0.1074, -0.0842, -0.1026, -0.0955, -0.0769, -0.0819, -0.0818, -0.0627,
        -0.0615, -0.0623, -0.0511, -0.04

In [62]:
e_vec[:, 0]

tensor([-0.0357, -0.0383, -0.0410, -0.0437, -0.0465, -0.0493, -0.0522, -0.0551,
        -0.0580, -0.0609, -0.0638, -0.0667, -0.0696, -0.0725, -0.0753, -0.0781,
        -0.0809, -0.0836, -0.0863, -0.0889, -0.0915, -0.0940, -0.0965, -0.0988,
        -0.1011, -0.1034, -0.1055, -0.1076, -0.1096, -0.1115, -0.1133, -0.1151,
        -0.1168, -0.1183, -0.1198, -0.1212, -0.1226, -0.1238, -0.1249, -0.1260,
        -0.1269, -0.1278, -0.1285, -0.1292, -0.1298, -0.1302, -0.1306, -0.1309,
        -0.1311, -0.1312, -0.1312, -0.1311, -0.1309, -0.1306, -0.1302, -0.1298,
        -0.1292, -0.1285, -0.1278, -0.1269, -0.1260, -0.1249, -0.1238, -0.1226,
        -0.1212, -0.1198, -0.1183, -0.1168, -0.1151, -0.1133, -0.1115, -0.1096,
        -0.1076, -0.1055, -0.1034, -0.1011, -0.0988, -0.0965, -0.0940, -0.0915,
        -0.0889, -0.0863, -0.0836, -0.0809, -0.0781, -0.0753, -0.0725, -0.0696,
        -0.0667, -0.0638, -0.0609, -0.0580, -0.0551, -0.0522, -0.0493, -0.0465,
        -0.0437, -0.0410, -0.0383, -0.03